# Generated by Django 5.1.1 on 2024-09-05 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(choices=[('Finance', 'Finance')], null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category'),
        ),
    ]
